FROM python:3.9-buster as build
RUN apt-get -y update && apt-get -y install python3 python3-pip
# https://github.com/googleapis/python-pubsub/issues/414
RUN pip install grpcio-tools==1.38.0 Flask==2.0.0 protobuf==3.15.2

ADD ./protos/ /protos
WORKDIR /protos
RUN ./build.sh

WORKDIR /
ADD webapp/ /app
RUN cp -r /protos/gen-py /app
COPY grpc-services/client_wrapper.py /app
WORKDIR /app
CMD ["/app/run-server.sh"]