FROM python:3.6-jessie
ADD protos/gen-py /protos/gen-py

ADD users/server /application
WORKDIR /application
RUN set -e; \
	apt-get update ; \
    apt-get install \
		gcc \
        g++ \
	; \
    pip install --upgrade pip; \
	pip install -r requirements.txt
EXPOSE 50051
VOLUME /application
CMD PYTHONPATH=/protos/gen-py python3 server.py
