# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eidentity.proto\"%\n\x14ValidateTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"%\n\x12ValidateTokenReply\x12\x0f\n\x07user_id\x18\x01 \x01(\t2I\n\x08Identity\x12=\n\rValidateToken\x12\x15.ValidateTokenRequest\x1a\x13.ValidateTokenReply\"\x00\x62\x06proto3')



_VALIDATETOKENREQUEST = DESCRIPTOR.message_types_by_name['ValidateTokenRequest']
_VALIDATETOKENREPLY = DESCRIPTOR.message_types_by_name['ValidateTokenReply']
ValidateTokenRequest = _reflection.GeneratedProtocolMessageType('ValidateTokenRequest', (_message.Message,), {
  'DESCRIPTOR' : _VALIDATETOKENREQUEST,
  '__module__' : 'identity_pb2'
  # @@protoc_insertion_point(class_scope:ValidateTokenRequest)
  })
_sym_db.RegisterMessage(ValidateTokenRequest)

ValidateTokenReply = _reflection.GeneratedProtocolMessageType('ValidateTokenReply', (_message.Message,), {
  'DESCRIPTOR' : _VALIDATETOKENREPLY,
  '__module__' : 'identity_pb2'
  # @@protoc_insertion_point(class_scope:ValidateTokenReply)
  })
_sym_db.RegisterMessage(ValidateTokenReply)

_IDENTITY = DESCRIPTOR.services_by_name['Identity']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VALIDATETOKENREQUEST._serialized_start=18
  _VALIDATETOKENREQUEST._serialized_end=55
  _VALIDATETOKENREPLY._serialized_start=57
  _VALIDATETOKENREPLY._serialized_end=94
  _IDENTITY._serialized_start=96
  _IDENTITY._serialized_end=169
# @@protoc_insertion_point(module_scope)
