# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eidentity.proto\"%\n\x14ValidateTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"%\n\x12ValidateTokenReply\x12\x0f\n\x07user_id\x18\x01 \x01(\t\",\n\x1bValidateFileDownloadRequest\x12\r\n\x05token\x18\x01 \x01(\t\",\n\x19ValidateFileDownloadReply\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"*\n\x19ValidateFileDeleteRequest\x12\r\n\x05token\x18\x01 \x01(\t\"*\n\x17ValidateFileDeleteReply\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"#\n\x12\x45xpireTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"\"\n\x10\x45xpireTokenReply\x12\x0e\n\x06result\x18\x01 \x01(\x08\x32\xa8\x02\n\x08Identity\x12=\n\rValidateToken\x12\x15.ValidateTokenRequest\x1a\x13.ValidateTokenReply\"\x00\x12R\n\x14ValidateFileDownload\x12\x1c.ValidateFileDownloadRequest\x1a\x1a.ValidateFileDownloadReply\"\x00\x12L\n\x12ValidateFileDelete\x12\x1a.ValidateFileDeleteRequest\x1a\x18.ValidateFileDeleteReply\"\x00\x12;\n\x0b\x45xpireToken\x12\x13.ExpireTokenRequest\x1a\x11.ExpireTokenReply\"\x00(\x01\x30\x01\x62\x06proto3')



_VALIDATETOKENREQUEST = DESCRIPTOR.message_types_by_name['ValidateTokenRequest']
_VALIDATETOKENREPLY = DESCRIPTOR.message_types_by_name['ValidateTokenReply']
_VALIDATEFILEDOWNLOADREQUEST = DESCRIPTOR.message_types_by_name['ValidateFileDownloadRequest']
_VALIDATEFILEDOWNLOADREPLY = DESCRIPTOR.message_types_by_name['ValidateFileDownloadReply']
_VALIDATEFILEDELETEREQUEST = DESCRIPTOR.message_types_by_name['ValidateFileDeleteRequest']
_VALIDATEFILEDELETEREPLY = DESCRIPTOR.message_types_by_name['ValidateFileDeleteReply']
_EXPIRETOKENREQUEST = DESCRIPTOR.message_types_by_name['ExpireTokenRequest']
_EXPIRETOKENREPLY = DESCRIPTOR.message_types_by_name['ExpireTokenReply']
ValidateTokenRequest = _reflection.GeneratedProtocolMessageType('ValidateTokenRequest', (_message.Message,), {
  'DESCRIPTOR' : _VALIDATETOKENREQUEST,
  '__module__' : 'identity_pb2'
  # @@protoc_insertion_point(class_scope:ValidateTokenRequest)
  })
_sym_db.RegisterMessage(ValidateTokenRequest)

ValidateTokenReply = _reflection.GeneratedProtocolMessageType('ValidateTokenReply', (_message.Message,), {
  'DESCRIPTOR' : _VALIDATETOKENREPLY,
  '__module__' : 'identity_pb2'
  # @@protoc_insertion_point(class_scope:ValidateTokenReply)
  })
_sym_db.RegisterMessage(ValidateTokenReply)

ValidateFileDownloadRequest = _reflection.GeneratedProtocolMessageType('ValidateFileDownloadRequest', (_message.Message,), {
  'DESCRIPTOR' : _VALIDATEFILEDOWNLOADREQUEST,
  '__module__' : 'identity_pb2'
  # @@protoc_insertion_point(class_scope:ValidateFileDownloadRequest)
  })
_sym_db.RegisterMessage(ValidateFileDownloadRequest)

ValidateFileDownloadReply = _reflection.GeneratedProtocolMessageType('ValidateFileDownloadReply', (_message.Message,), {
  'DESCRIPTOR' : _VALIDATEFILEDOWNLOADREPLY,
  '__module__' : 'identity_pb2'
  # @@protoc_insertion_point(class_scope:ValidateFileDownloadReply)
  })
_sym_db.RegisterMessage(ValidateFileDownloadReply)

ValidateFileDeleteRequest = _reflection.GeneratedProtocolMessageType('ValidateFileDeleteRequest', (_message.Message,), {
  'DESCRIPTOR' : _VALIDATEFILEDELETEREQUEST,
  '__module__' : 'identity_pb2'
  # @@protoc_insertion_point(class_scope:ValidateFileDeleteRequest)
  })
_sym_db.RegisterMessage(ValidateFileDeleteRequest)

ValidateFileDeleteReply = _reflection.GeneratedProtocolMessageType('ValidateFileDeleteReply', (_message.Message,), {
  'DESCRIPTOR' : _VALIDATEFILEDELETEREPLY,
  '__module__' : 'identity_pb2'
  # @@protoc_insertion_point(class_scope:ValidateFileDeleteReply)
  })
_sym_db.RegisterMessage(ValidateFileDeleteReply)

ExpireTokenRequest = _reflection.GeneratedProtocolMessageType('ExpireTokenRequest', (_message.Message,), {
  'DESCRIPTOR' : _EXPIRETOKENREQUEST,
  '__module__' : 'identity_pb2'
  # @@protoc_insertion_point(class_scope:ExpireTokenRequest)
  })
_sym_db.RegisterMessage(ExpireTokenRequest)

ExpireTokenReply = _reflection.GeneratedProtocolMessageType('ExpireTokenReply', (_message.Message,), {
  'DESCRIPTOR' : _EXPIRETOKENREPLY,
  '__module__' : 'identity_pb2'
  # @@protoc_insertion_point(class_scope:ExpireTokenReply)
  })
_sym_db.RegisterMessage(ExpireTokenReply)

_IDENTITY = DESCRIPTOR.services_by_name['Identity']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VALIDATETOKENREQUEST._serialized_start=18
  _VALIDATETOKENREQUEST._serialized_end=55
  _VALIDATETOKENREPLY._serialized_start=57
  _VALIDATETOKENREPLY._serialized_end=94
  _VALIDATEFILEDOWNLOADREQUEST._serialized_start=96
  _VALIDATEFILEDOWNLOADREQUEST._serialized_end=140
  _VALIDATEFILEDOWNLOADREPLY._serialized_start=142
  _VALIDATEFILEDOWNLOADREPLY._serialized_end=186
  _VALIDATEFILEDELETEREQUEST._serialized_start=188
  _VALIDATEFILEDELETEREQUEST._serialized_end=230
  _VALIDATEFILEDELETEREPLY._serialized_start=232
  _VALIDATEFILEDELETEREPLY._serialized_end=274
  _EXPIRETOKENREQUEST._serialized_start=276
  _EXPIRETOKENREQUEST._serialized_end=311
  _EXPIRETOKENREPLY._serialized_start=313
  _EXPIRETOKENREPLY._serialized_end=347
  _IDENTITY._serialized_start=350
  _IDENTITY._serialized_end=646
# @@protoc_insertion_point(module_scope)
