FROM python:3.9-buster as build
RUN apt-get -y update && apt-get -y install python3 python3-pip
RUN pip install grpcio-tools==1.38.0 python-json-logger==2.0.1 datadog==0.41.0

ADD protos /protos
WORKDIR /protos
RUN ./build.sh

WORKDIR /
ADD grpc-services/users /app
RUN cp -r /protos/gen-py /app
WORKDIR /app
CMD ["/app/run-server.sh"]
