# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import users_types_pb2 as users__types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='users.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0busers.proto\x1a\x11users_types.proto2\x83\x01\n\x05Users\x12?\n\nCreateUser\x12\x18.users.CreateUserRequest\x1a\x17.users.CreateUserResult\x12\x39\n\x08GetUsers\x12\x16.users.GetUsersRequest\x1a\x15.users.GetUsersResultb\x06proto3')
  ,
  dependencies=[users__types__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class UsersStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.CreateUser = channel.unary_unary(
          '/Users/CreateUser',
          request_serializer=users__types__pb2.CreateUserRequest.SerializeToString,
          response_deserializer=users__types__pb2.CreateUserResult.FromString,
          )
      self.GetUsers = channel.unary_unary(
          '/Users/GetUsers',
          request_serializer=users__types__pb2.GetUsersRequest.SerializeToString,
          response_deserializer=users__types__pb2.GetUsersResult.FromString,
          )


  class UsersServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def CreateUser(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def GetUsers(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_UsersServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'CreateUser': grpc.unary_unary_rpc_method_handler(
            servicer.CreateUser,
            request_deserializer=users__types__pb2.CreateUserRequest.FromString,
            response_serializer=users__types__pb2.CreateUserResult.SerializeToString,
        ),
        'GetUsers': grpc.unary_unary_rpc_method_handler(
            servicer.GetUsers,
            request_deserializer=users__types__pb2.GetUsersRequest.FromString,
            response_serializer=users__types__pb2.GetUsersResult.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'Users', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaUsersServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def CreateUser(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def GetUsers(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaUsersStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def CreateUser(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    CreateUser.future = None
    def GetUsers(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    GetUsers.future = None


  def beta_create_Users_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('Users', 'CreateUser'): users__types__pb2.CreateUserRequest.FromString,
      ('Users', 'GetUsers'): users__types__pb2.GetUsersRequest.FromString,
    }
    response_serializers = {
      ('Users', 'CreateUser'): users__types__pb2.CreateUserResult.SerializeToString,
      ('Users', 'GetUsers'): users__types__pb2.GetUsersResult.SerializeToString,
    }
    method_implementations = {
      ('Users', 'CreateUser'): face_utilities.unary_unary_inline(servicer.CreateUser),
      ('Users', 'GetUsers'): face_utilities.unary_unary_inline(servicer.GetUsers),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_Users_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('Users', 'CreateUser'): users__types__pb2.CreateUserRequest.SerializeToString,
      ('Users', 'GetUsers'): users__types__pb2.GetUsersRequest.SerializeToString,
    }
    response_deserializers = {
      ('Users', 'CreateUser'): users__types__pb2.CreateUserResult.FromString,
      ('Users', 'GetUsers'): users__types__pb2.GetUsersResult.FromString,
    }
    cardinalities = {
      'CreateUser': cardinality.Cardinality.UNARY_UNARY,
      'GetUsers': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'Users', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
